### ISSUE TITLE
some questions about classifier layer for the model

### ISSUE THREAD

**Issue by whySnowwW** [blue-blue272/fewshot-CAN#10]
Dear auther
there is some question in my mind: in the train stage, the num_classes is 64 which is the number of the miniImageNet_train.pickle, however, when i use the test.py to evaluate my model ,the num_classes is still 64 in the model , I'm a little confused about the few shot model's test principle.
Thank you for your time reading my issues. Best wishes!

**Comment by blue-blue272** [comment]
Our method is based on the prototype network. In the testing phase, the classifier is not used, we only use the feature extractor part.

**Comment by whySnowwW** [comment]
Thanks for your reply. What is the code test transductive used for？ and which is the meta learner in the code, I just find myself troublesome in finding the meta learner part of the model structure

**Comment by blue-blue272** [comment]
The test transductive is for the few-shot classification in the transductive setting. You can find the details in the **Transductive Inference** part of Section 4 in our paper. 
The meta-learner is the get_attention function in the cam.py, the details can be seen in **Meta fusion Layer** in Section 3 in our paper.

**Comment by whySnowwW** [comment]
Sorry to disturb you ,but i still can't find the meta learner part in the code cam.py. Whether it is lying in the part of the def get_attention?

**Comment by Medallion11** [comment]
> Sorry to disturb you ,but i still can't find the meta learner part in the code cam.py. Whether it is lying in the part of the def get_attention?

i also find the meta learner,did you find out now?
