### ISSUE TITLE
a question about residual attention mechanism

### ISSUE THREAD

**Issue by howyoungchen** [blue-blue272/fewshot-CAN#11]
in the residual attention mechanism,the initial feature maps P and Q are elementwisely weighted by **1 + A^p and 1 + A^q**.
I guess that the line` f1 = f1.unsqueeze(2) * a1.unsqueeze(3) `in cam.py is the elementwisely weighted operation.
However I can't find the operation of **(1+)** in your code.

I am deeply inspired by the excellent programming of this project. Thanks for your kindly sharing  and look forward to your early reply.

**Comment by blue-blue272** [comment]
It is in the line 52 in cam.py
