### ISSUE TITLE
关于代码的问题

### ISSUE THREAD

**Issue by plzhong309** [blue-blue272/fewshot-CAN#13]
您好：
您的代码很简洁，方法的效果也是sota。
但是我想请教一下，您在meta-train之前是否在base class上做过预训练呢？我直接运行您提供的train.py（所有参数均未改动），得到的结果只有百分之二十多？不知道是哪里出了问题，希望能得到您的回复，谢谢！

**Comment by zhouyi11111** [comment]
> 您好： 您的代码很简洁，方法的效果也是sota。 但是我想请教一下，您在meta-train之前是否在base class上做过预训练呢？我直接运行您提供的train.py（所有参数均未改动），得到的结果只有百分之二十多？不知道是哪里出了问题，希望能得到您的回复，谢谢！

你好，请问你解决了吗

**Comment by plzhong309** [comment]
您好，
&nbsp; &nbsp; &nbsp; &nbsp;很抱歉才看到您的邮件，我联系过作者，但是没有回复，我也没有在这个问题上继续深入研究。
&nbsp; &nbsp; &nbsp; &nbsp;如果您已解决的话，我也想向您请教一下您是如何处理的，谢谢！
&nbsp; &nbsp; &nbsp; &nbsp;春节将至，提前祝您新春快乐！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blue-blue272/fewshot-CAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月23日(星期三) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blue-blue272/fewshot-CAN] 关于代码的问题 (Issue #13)





  
您好： 您的代码很简洁，方法的效果也是sota。 但是我想请教一下，您在meta-train之前是否在base class上做过预训练呢？我直接运行您提供的train.py（所有参数均未改动），得到的结果只有百分之二十多？不知道是哪里出了问题，希望能得到您的回复，谢谢！
  
你好，请问你解决了吗

**Comment by blue-blue272** [comment]
> 您好： 您的代码很简洁，方法的效果也是sota。 但是我想请教一下，您在meta-train之前是否在base class上做过预训练呢？我直接运行您提供的train.py（所有参数均未改动），得到的结果只有百分之二十多？不知道是哪里出了问题，希望能得到您的回复，谢谢！

没有经过预训练。直接运行应该能得出结果的。可能是数据输入格式的问题？
