### ISSUE TITLE
some problem about trainning miniimagenet.

### ISSUE THREAD

**Issue by ljjcoder** [blue-blue272/fewshot-CAN#3]
Thanks for your excellent work! When I train the model on miniimagenet, i only get the accuracy with 78.84%(5-shot), which is lower than your result in your paper。Can you give me some advise to reproduce your result in paper？ 
![1577089624](https://user-images.githubusercontent.com/40750189/71346146-27bf4e80-25a2-11ea-8f63-32a601ea3c5d.png)

**Comment by blue-blue272** [comment]
In my paper, the performance is 79.44%. It is normal to have these performance gap.
