### ISSUE TITLE
关于如何跑代码的问题

### ISSUE THREAD

**Issue by Wongcheukwai** [blue-blue272/fewshot-CAN#5]
您好
您的代码很简洁，方法的效果也很好，效果也是sota。但是我想问问该如何运行您的程序，需要配置什么环境，因为您好像没有说明该如何跑程序，谢谢。

**Comment by blue-blue272** [comment]
python train.py 参数使用args_xent.py(miniImageNet)和args_tiered.py（tieredImageNet）默认的参数
