### ISSUE TITLE
Where are the codes for the part of "Transductive Inference" ?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [blue-blue272/fewshot-CAN#6]
Hi, @blue-blue272! 
I think this is an interesting and inspiring work, but in your released code, I don't find the code for  "Transductive Inference" as shown in your paper. Maybe I don't find it. Can you point it out for me? 
In your released code(default settings in args_xent.py), I also find that you use the test dataset to early stop, I don't think it's appropriate.
 Looking forward to your reply!

**Comment by blue-blue272** [comment]
I have updated the transductive code. You can run the test_transductive.py for the transductive inference.

It is appropriate to set the phase to 'val'. I got a similar performance for both settings.
