### ISSUE TITLE
关于数据库的问题

### ISSUE THREAD

**Issue by Wongcheukwai** [blue-blue272/fewshot-CAN#7]
不好意思 再打扰一下，请问
1.数据库的话tieredImageNet和miniImageNet都是从mengye和matchingnet的官网上下载吗？
2.关于下载后的处理，我看到您dataset里面有miniImageNet.py和miniImageNet_load.py，但是他们的路径不一样，然后args_xent.py里面dataset参数为miniImageNet_load，是不是意味着就是读取miniimaget的数据时只用了miniImageNet_load.py？
3.不得不说您的算法真的很简洁很明了，是我们学习的榜样
4.请问一下transductive部分的代码是没有公布吗？
谢谢您的耐心

**Comment by blue-blue272** [comment]
1. 具体的数据集下载可以参考‘https://github.com/kjunelee/MetaOptNet’
2. 我才用的是miniImageNet_load读取miniImageNet
4. 我们已经上传了transductive部分的代码，您可以运行test_transductive.py
